## https://github.com/schollz/croc
##
{{ $croc_version := "9.6.0" }}
{{ $croc_package := "" }}
{{- if (eq .chezmoi.os "darwin") }}
{{   $croc_package = (printf "croc_%s_macOS-64bit.tar.gz" $croc_version) }}
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
{{   $croc_package = (printf "croc_%s_Linux-64bit.tar.gz" $croc_version) }}
{{- end }}
{{ $croc_url := (printf "https://github.com/schollz/croc/releases/download/v%s/%s" $croc_version $croc_package) }}

{{ with $croc_package }}
["croc"]
    type = "archive"
    url = "{{ $croc_url }}"
    exact = true
    refreshPeriod = "168h"
{{ end }}

## https://github.com/ogham/exa
##
{{ $exa_version := "v0.10.1" }}
{{ $exa_package := "" }}
{{- if (eq .chezmoi.os "darwin") }}
{{   $exa_package = (printf "exa-macos-x86_64-%s.zip" $exa_version) }}
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
{{   $exa_package = (printf "exa-linux-x86_64-musl-%s.zip" $exa_version) }}
{{- end }}
{{ $exa_url := (printf "https://github.com/ogham/exa/releases/download/%s/%s" $exa_version $exa_package) }}

{{ with $exa_package }}
["exa"]
    type = "archive"
    url = "{{ $exa_url }}"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{ end }}

## https://github.com/sharkdp/fd
##
{{ $fd_version := "v8.4.0" }}
{{ $fd_package := "" }}
{{- if (eq .chezmoi.os "darwin") }}
{{   $fd_package = (printf "fd-%s-x86_64-apple-darwin.tar.gz" $fd_version) }}
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
{{   $fd_package = (printf "fd-%s-x86_64-unknown-linux-musl.tar.gz" $fd_version) }}
{{- end }}
{{ $fd_url := (printf "https://github.com/sharkdp/fd/releases/download/%s/%s" $fd_version $fd_package) }}

{{ with $fd_package }}
["fd"]
    type = "archive"
    url = "{{ $fd_url }}"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{ end }}

## https://github.com/sharkdp/hexyl
##
{{ $hexyl_version := "v0.9.0" }}
{{ $hexyl_package := "" }}
{{- if (eq .chezmoi.os "darwin") }}
{{   $hexyl_package = (printf "hexyl-%s-x86_64-apple-darwin.tar.gz" $hexyl_version) }}
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
{{   $hexyl_package = (printf "hexyl-%s-x86_64-unknown-linux-musl.tar.gz" $hexyl_version) }}
{{- end }}
{{ $hexyl_url := (printf "https://github.com/sharkdp/hexyl/releases/download/%s/%s" $hexyl_version $hexyl_package) }}

{{ with $hexyl_package }}
["hexyl"]
    type = "archive"
    url = "{{ $hexyl_url }}"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{ end }}

## https://github.com/BurntSushi/ripgrep
##
{{ $ripgrep_version := "13.0.0" }}
{{ $ripgrep_package := "" }}
{{- if (eq .chezmoi.os "darwin") }}
{{   $ripgrep_package = (printf "ripgrep-%s-x86_64-apple-darwin.tar.gz" $ripgrep_version) }}
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
{{   $ripgrep_package = (printf "ripgrep-%s-x86_64-unknown-linux-musl.tar.gz" $ripgrep_version) }}
{{- end }}
{{ $ripgrep_url := (printf "https://github.com/BurntSushi/ripgrep/releases/download/%s/%s" $ripgrep_version $ripgrep_package) }}

{{ with $ripgrep_package }}
["ripgrep"]
    type = "archive"
    url = "{{ $ripgrep_url }}"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{ end }}

## https://github.com/zellij-org/zellij
##
{{ $zellij_version := "v0.25.0" }}
{{ $zellij_package := "" }}
{{- if (eq .chezmoi.os "darwin") }}
{{   $zellij_package = "zellij-x86_64-apple-darwin.tar.gz" }}
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
{{   $zellij_package = "zellij-x86_64-unknown-linux-musl.tar.gz" }}
{{- end }}
{{ $zellij_url := (printf "https://github.com/zellij-org/zellij/releases/download/%s/%s" $zellij_version $zellij_package) }}

{{ with $zellij_package }}
["zellij"]
    type = "archive"
    url = "{{ $zellij_url }}"
    exact = true
    refreshPeriod = "168h"
{{ end }}

## https://github.com/bvaisvil/zenith
##
{{ $zenith_version := "0.12.0" }}
{{ $zenith_package := "" }}
{{- if (eq .chezmoi.os "darwin") }}
{{   $zenith_package = "zenith.x86_64_MacOS.tgz" }}
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
{{   $zenith_package = "zenith.x86_64-unknown-linux-musl.tgz" }}
{{- end }}
{{ $zenith_url := (printf "https://github.com/bvaisvil/zenith/releases/download/%s/%s" $zenith_version $zenith_package) }}

{{ with $zenith_package }}
["zenith"]
    type = "archive"
    url = "{{ $zenith_url }}"
    exact = true
    refreshPeriod = "168h"
{{ end }}
