{{ $values := . }}

{{- /* include GitHub external */ -}}
{{- $externalGithub := glob (joinPath .chezmoi.sourceDir "dot_local/cli/.github.com" "*json") }}
{{- range $_, $path := $externalGithub }}
{{-   $content := include $path }}
{{-   $external := fromJson $content }}
{{- /* make a copy of values */ -}}
{{-   $values_copy := $values | deepCopy }}
{{-   $_ := set $values_copy "this" $external }}
{{- /* include entry */ -}}
{{    includeTemplate "external_github.toml.tmpl" $values_copy }}
{{- end -}}
