["exa"]
{{ $exa_version := "v0.10.1" }}
    type = "archive"
{{- if (eq .chezmoi.os "darwin") }}
    url = "https://github.com/ogham/exa/releases/download/{{ $exa_version }}/exa-macos-x86_64-{{ $exa_version }}.zip"
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
    url = "https://github.com/ogham/exa/releases/download/{{ $exa_version }}/exa-linux-x86_64-musl-{{ $exa_version }}.zip"
{{- end }}
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["fd"]
{{ $fd_version := "v8.3.2" }}
    type = "archive"
{{- if (eq .chezmoi.os "darwin") }}
    url = "https://github.com/sharkdp/fd/releases/download/{{ $fd_version }}/fd-{{ $fd_version }}-x86_64-apple-darwin.tar.gz"
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
    url = "https://github.com/sharkdp/fd/releases/download/{{ $fd_version }}/fd-{{ $fd_version }}-x86_64-unknown-linux-musl.tar.gz"
{{- end }}
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["ripgrep"]
{{ $ripgrep_version := "13.0.0" }}
    type = "archive"
{{- if (eq .chezmoi.os "darwin") }}
    url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ $ripgrep_version }}/ripgrep-{{ $ripgrep_version }}-x86_64-apple-darwin.tar.gz"
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
    url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ $ripgrep_version }}/ripgrep-{{ $ripgrep_version }}-x86_64-unknown-linux-musl.tar.gz"
{{- end }}
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["hexyl"]
{{ $hexyl_version := "v0.9.0" }}
    type = "archive"
{{- if (eq .chezmoi.os "darwin") }}
    url = "https://github.com/sharkdp/hexyl/releases/download/{{ $hexyl_version }}/hexyl-{{ $hexyl_version }}-x86_64-apple-darwin.tar.gz"
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
    url = "https://github.com/sharkdp/hexyl/releases/download/{{ $hexyl_version }}/hexyl-{{ $hexyl_version }}-x86_64-unknown-linux-musl.tar.gz"
{{- end }}
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["zellij"]
{{ $zellij_version := "v0.24.0" }}
    type = "archive"
{{- if (eq .chezmoi.os "darwin") }}
    url = "https://github.com/zellij-org/zellij/releases/download/{{ $zellij_version }}/zellij-x86_64-apple-darwin.tar.gz"
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
    url = "https://github.com/zellij-org/zellij/releases/download/{{ $zellij_version }}/zellij-aarch64-unknown-linux-musl.tar.gz"
{{- end }}
    exact = true
    refreshPeriod = "168h"
["zenith"]
{{ $zenith_version := "0.12.0" }}
    type = "archive"
{{- if (eq .chezmoi.os "darwin") }}
    url = "https://github.com/bvaisvil/zenith/releases/download/{{ $zenith_version }}/zenith.x86_64_MacOS.tgz"
{{- end }}
{{- if (eq .chezmoi.os "linux") }}
    url = "https://github.com/bvaisvil/zenith/releases/download/{{ $zenith_version }}/zenith.x86_64-unknown-linux-musl.tgz"
{{- end }}
    exact = true
    refreshPeriod = "168h"
