[tools]
"github:bokwoon95/wgo" = "v0.6.4"
"github:joho/godotenv" = "1.5.1"
"github:junegunn/fzf" = "0.73.1"
"github:kavehtehrani/cloudflare-speed-cli" = "1.0.6"
"github:sxyazi/yazi" = "26.5.6"
"github:trasta298/keifu" = "0.4.0"
"github:trzsz/trzsz-ssh" = "0.1.25"
"github:trzsz/tsshd" = "0.1.8"
