name: CI

on:
  push:
    branches:
      - main
      - renovate/**
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test-linux-amd64:
    runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use local install-action
        uses: ./.github/actions/install-action

  test-linux-arm64:
    if: ${{ vars.RUNNER_ARM }}
    runs-on: ${{ vars.RUNNER_ARM }}
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use local install-action
        uses: ./.github/actions/install-action
